name: C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ python3-pip
          python3 -m pip install --upgrade pip
          pip3 install conan

      - name: Configure Conan
        run: |
          echo "Configure Conan"

      - name: Install dependencies with Conan
        run: |
          echo "Install dependencies with Conan"

      - name: Build project
        run: |
          echo "Build project"

      - name: Run unit tests
        run: |
          echo "Run unit tests"

      - name: Run benchmarks
        run: |
          echo "Run benchmarks"